### ISSUE TITLE
Confusing URL in publishing process

### ISSUE THREAD

**Issue by tomhukins** [davorg/learncpan#11]
Hi, Dave.  Thank you for creating and maintaining this useful collection of tutorials.

The [build and deployment](https://github.com/davorg/learncpan/actions/runs/2775369470) action for this repository shows the URL http://davorg.dev/learncpan/ under the "deploy" action.  This URL returns a 404.

It would be helpful for this workflow to show the address the deployment system deploys to.  It might also be worth mentioning this in the README.md.

**Comment by davorg** [comment]
Hi Tom,

Yeah, I can see how that was confusing. I've now added a (completely basic) index.html which contains a link to the actual data (http://davorg.dev/learncpan/tutorials.json) and added a link to the README as well.

Thanks for pointing that out.
